# Generated by Django 4.1.1 on 2022-09-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
