# Generated by Django 4.1.1 on 2022-09-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeUser', '0003_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(max_length=12),
        ),
    ]
